services:
  - type: web
    name: libretranslate
    env: docker
    repo: https://github.com/olelasbs/LibreTranslate
    branch: main
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    autoDeploy: true
